import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ArrowRight,Check,ChevronRight,Layers,ScanLine,SlidersHorizontal,Activity,RotateCcw,Box,FileText,ShieldCheck,AlertTriangle,Search,X,GitBranch} from 'lucide-react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import '@fontsource-variable/noto-sans-kr';
import '@fontsource-variable/dm-sans';
import './style.css';
type Fact={id:string;field:string;value:string|{low:string;high:string};unit?:string;source:{bbox?:number[]}};
type Doc={id:string;drawing_number:string;revision_label:string;title:string;active:boolean;facts:Fact[]};
type Evidence={field:string;verdict:string;summary:string;source_refs:{bbox?:number[]}[]};
type Decision={revision_id:string;verdict:string;evidence:Evidence[]};
type Run={id:string;state:string;decisions:Decision[];snapshot_id:string;error?:string;usage:{tool_calls:number;model_calls:number;input_tokens:number;output_tokens:number}};
type Event={seq:number;kind:string;timestamp:string;payload:Record<string,unknown>};
const labels:Record<string,string>={match:'조건 일치',mismatch:'조건 불일치',unknown:'확인 필요'};
const fields:Record<string,string>={hole_spacing:'구멍 간격',material:'소재',width:'너비',kind:'부품 종류',height:'높이',thickness:'두께'};
const eventNames:Record<string,string>={queued:'검증 요청 접수',started:'작업 시작',claimed:'작업 시작',intent:'요청 조건 구조화',retrieved:'후보 도면 검색',tool:'원본 근거 조회',verified:'조건 판정',completed:'결과 저장',interrupted:'worker 중단 · checkpoint 보존',resumed:'저장된 지점에서 재개',stale:'도면 변경 감지',model:'모델 응답 수신',failed:'실행 실패',cancelled:'실행 취소'};
async function api<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch('/api'+path,{...init,headers:{'Content-Type':'application/json',...init?.headers}});if(!r.ok){const x=await r.json().catch(()=>({detail:r.statusText}));throw Error(typeof x.detail==='string'?x.detail:JSON.stringify(x.detail));}return r.json();}
const asset=(id:string,type:string)=>`/api/documents/${id}/assets/${type}`;
const fmt=(f?:Fact)=>!f?'표기 없음':typeof f.value==='string'?f.value:`${f.value.low}${f.value.low===f.value.high?'':`–${f.value.high}`} ${f.unit||''}`;
function Model({id}:{id:string}){const ref=useRef<HTMLDivElement>(null);const [err,setErr]=useState('');useEffect(()=>{const el=ref.current!;let disposed=false;let renderer:THREE.WebGLRenderer;let cleanup=()=>{};fetch(asset(id,'mesh')).then(r=>r.json()).then(data=>{if(disposed)return;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(el.clientWidth,300);el.appendChild(renderer.domElement);const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(35,el.clientWidth/300,.1,10000);const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(data.vertices.flat(),3));geometry.setIndex(data.faces.flat());geometry.computeVertexNormals();geometry.computeBoundingSphere();const sphere=geometry.boundingSphere!;geometry.translate(-sphere.center.x,-sphere.center.y,-sphere.center.z);const material=new THREE.MeshStandardMaterial({color:0x409c8d,metalness:.35,roughness:.5});const mesh=new THREE.Mesh(geometry,material);scene.add(mesh,new THREE.HemisphereLight(0xffffff,0x4a6671,3));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(80,100,150);scene.add(light);camera.position.set(sphere.radius*2,sphere.radius*1.5,sphere.radius*2.5);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;const observer=new ResizeObserver(()=>{renderer.setSize(el.clientWidth,300);camera.aspect=el.clientWidth/300;camera.updateProjectionMatrix();});observer.observe(el);renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});cleanup=()=>{observer.disconnect();controls.dispose();renderer.dispose();geometry.dispose();material.dispose();renderer.domElement.remove();};}catch{setErr('이 브라우저에서는 3D를 표시할 수 없습니다. STEP 파일을 내려받아 확인해 주세요.');}}).catch(()=>setErr('3D 파일을 불러오지 못했습니다.'));return()=>{disposed=true;cleanup();};},[id]);return <div className="model" ref={ref}>{err&&<p>{err}</p>}<span>드래그하여 회전 · 스크롤하여 확대</span></div>}
function App(){const [ready,setReady]=useState(false),[docs,setDocs]=useState<Doc[]>([]),[query,setQuery]=useState('장비에 고정할 브래킷을 찾아줘'),[spacing,setSpacing]=useState('40'),[material,setMaterial]=useState('SUS304'),[provider,setProvider]=useState('rules'),[providers,setProviders]=useState<Record<string,boolean>>({rules:true}),[run,setRun]=useState<Run|null>(null),[events,setEvents]=useState<Event[]>([]),[selected,setSelected]=useState<string>(''),[field,setField]=useState('hole_spacing'),[view,setView]=useState('2d'),[fault,setFault]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[timeline,setTimeline]=useState(false),[revised,setRevised]=useState(false),[tab,setTab]=useState('work'),[evaluation,setEvaluation]=useState<any>(null);
 const initialized=useRef(false);const reload=()=>api<Doc[]>('/documents').then(setDocs);
 useEffect(()=>{if(initialized.current)return;initialized.current=true;(async()=>{try{await api('/demo-sessions',{method:'POST'});await reload();const c=await api<{providers:Record<string,boolean>}>('/capabilities');setProviders(c.providers);setReady(true);}catch(e){setError(String(e));}})();},[]);
 useEffect(()=>{if(!run||!['queued','running','retry_wait'].includes(run.state))return;let stopped=false;const poll=async()=>{try{const [r,e]=await Promise.all([api<Run>('/runs/'+run.id),api<Event[]>('/runs/'+run.id+'/events')]);if(!stopped){setRun(r);setEvents(e);if(r.decisions.length)setSelected(v=>v||r.decisions[0].revision_id);if(r.error)setError(r.error);}}catch(e){if(!stopped)setError(String(e));}};const t=setInterval(poll,700);void poll();return()=>{stopped=true;clearInterval(t);};},[run?.id,run?.state]);
 const running=busy||!!run&&['queued','running','retry_wait'].includes(run.state);
 async function start(){setError('');setBusy(true);setSelected('');setEvents([]);try{const value=Number(spacing);if(!Number.isFinite(value)||value<=0)throw Error('간격은 0보다 큰 숫자로 입력해 주세요.');const r=await api<Run>('/runs',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID(),...(fault?{'x-demo-fault':'1'}:{})},body:JSON.stringify({search:{text:query+' 브래킷',requirements:[{field:'hole_spacing',value:{low:String(value),high:String(value)},unit:'mm'},{field:'material',value:material}]},provider})});setRun(r);}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function revise(){setBusy(true);setError('');try{await api('/demo/revision',{method:'POST'});setRevised(true);await reload();if(run)setRun(await api<Run>('/runs/'+run.id));}catch(e){setError(String(e));}finally{setBusy(false);}}
 const decisions=run?.decisions||[];const doc=docs.find(d=>d.id===selected);const decision=decisions.find(d=>d.revision_id===selected);const evidence=decision?.evidence.find(e=>e.field===field);const bbox=evidence?.source_refs[0]?.bbox;const active=docs.filter(d=>d.active);const state=run?.state==='completed'?'검증 완료':run?.state==='stale'?'재검증 필요':running?'근거를 확인하고 있습니다':run?.state==='failed'?'실행 실패':run?.state==='cancelled'?'실행 취소':'검증 준비';
 return <><header><a className="brand" href="/"><span className="brand-icon"><Layers size={23}/></span>FitWitness<span className="beta">LAB</span></a><nav><button className={tab==='work'?'active':''} onClick={()=>setTab('work')}><ScanLine size={15}/> 검증 워크스페이스</button><button className={tab==='eval'?'active':''} onClick={()=>{setTab('eval');api('/evaluations').then(setEvaluation).catch(e=>setError(String(e)));}}><Activity size={15}/> 실험 리포트</button></nav><span className="session"><i/>{ready?'독립 체험 공간':'체험 공간 준비 중'}</span><a className="github" href="https://github.com/sokldjs554/fitwitness" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={14}/></a></header>
 <main><div className="intro"><div><div className="eyebrow">ENGINEERING EVIDENCE WORKSPACE <span>01 / DRAWING INTELLIGENCE</span></div><h1>도면의 생김새보다, 맞는 근거.</h1><p>닮은 부품 사이의 작은 차이. 치수와 소재를 원본에서 확인하고, 개정 이후에도 판단을 지킵니다.</p></div><div className="corpus"><span>DEMO COLLECTION</span><strong>{active.length.toString().padStart(2,'0')} <small>개의 유사 도면</small></strong><span>합성 CAD · 실제 PDF / STEP</span></div></div>
 {error&&<div role="alert" className="error"><AlertTriangle size={18}/>{error}<button aria-label="오류 닫기" onClick={()=>setError('')}><X size={16}/></button></div>}
 {tab==='eval'?<section className="eval-page"><span className="eyebrow">MEASURE BEFORE YOU CLAIM</span><h2>측정된 결과만 보여드립니다.</h2>{evaluation?.status==='measured'?<><p>{evaluation.description}</p><div className="eval-grid">{Object.entries(evaluation.metrics||{}).map(([k,v])=><article key={k}><span>{k}</span><strong>{String(v)}</strong></article>)}</div><pre>{JSON.stringify(evaluation,null,2)}</pre></>:<p>{evaluation?.message||'실험 리포트를 불러오는 중입니다.'}</p>}<p className="muted">규칙 기반 검증과 유료 LLM 실험은 구분하여 기록합니다. 합성 데이터 결과는 실제 제조 현장의 정확도를 의미하지 않습니다.</p></section>:<>
 <div className="scenario-strip"><span><span className="mini-num">1</span> 조건으로 찾기</span><ChevronRight size={14}/><span><span className="mini-num">2</span> 원본 근거 확인</span><ChevronRight size={14}/><span><span className="mini-num">3</span> 개정판 재검증</span><span className="scenario-note">체험 데이터는 작업 공간마다 격리됩니다.</span></div>
 <div className="workspace"><aside className="request-panel"><div className="panel-title"><SlidersHorizontal size={17}/><h2>찾는 부품의 조건</h2><span>01</span></div><label htmlFor="query">어떤 부품이 필요한가요?</label><textarea id="query" value={query} onChange={e=>setQuery(e.target.value)} rows={3}/><div className="field-label">필수 조건 <span>원본 표기로 검증</span></div><label className="input-label" htmlFor="spacing">구멍 중심 간격</label><div className="unit-input"><input id="spacing" type="number" min="0.01" step="0.1" value={spacing} onChange={e=>setSpacing(e.target.value)}/><span>mm</span></div><label className="input-label" htmlFor="material">소재</label><select id="material" value={material} onChange={e=>setMaterial(e.target.value)}><option>SUS304</option><option>AL6061</option></select><div className="condition-note"><ShieldCheck size={15}/><span>근거가 없으면 추측하지 않고<br/><b>확인 필요</b>로 남깁니다.</span></div><hr/><label className="input-label" htmlFor="provider">실행 엔진</label><select id="provider" value={provider} onChange={e=>setProvider(e.target.value)}><option value="rules">규칙 기반 · API 키 없이 체험</option><option value="openai" disabled={!providers.openai}>OpenAI{!providers.openai?' · 연결 필요':''}</option><option value="anthropic" disabled={!providers.anthropic}>Claude{!providers.anthropic?' · 연결 필요':''}</option></select><p className="engine-note">현재 엔진은 PDF의 표기와 단위 변환을 직접 대조합니다. LLM 호출을 흉내 내지 않습니다.</p><button className="primary" onClick={start} disabled={!ready||running}><Search size={16}/>{running?'검증 중…':'조건 검증 시작'}<ArrowRight size={16}/></button><label className="checkbox"><input type="checkbox" checked={fault} onChange={e=>setFault(e.target.checked)} disabled={running}/>중간 중단 후 복구 체험</label><div className="mini-card"><GitBranch size={18}/><div><b>도면이 바뀌면, 판단도 바뀝니다.</b><p>Rev. B에서 간격 40 → 42 mm.<br/>기존 결과의 유효성을 확인해 보세요.</p><button className="text-button" disabled={!ready||running||revised} onClick={revise}>{revised?'Rev. B 적용됨':'개정판 적용'} <ArrowUpRight size={14}/></button></div></div></aside>
 <section className="results-panel"><div className="panel-title"><Layers size={17}/><h2>후보 도면</h2><span>{decisions.length||active.length}</span></div><div className="result-status"><span className={running?'pulse status':`status ${run?.state==='stale'?'warn':''}`}><i/>{state}</span><span>{run?`실행 ${run.id.slice(0,8)}`:'조건을 입력하고 검증을 시작하세요'}</span></div>{run?.state==='stale'&&<div className="stale"><AlertTriangle size={17}/><p>검증 후 도면이 변경되었습니다. 이전 결과로 부품을 선택하지 마세요.</p><button onClick={start} disabled={running}>바뀐 도면으로 재검증 <RotateCcw size={13}/></button></div>}
 {decisions.length>0&&<div className="counts">{['match','unknown','mismatch'].map(v=><span key={v} className={v}><i/>{labels[v]} <b>{decisions.filter(d=>d.verdict===v).length}</b></span>)}</div>}
 <div className="candidates">{(decisions.length?decisions.map(d=>({doc:docs.find(x=>x.id===d.revision_id),decision:d})):active.map(doc=>({doc,decision:undefined}))).filter(x=>x.doc).map(({doc:d,decision:c})=><button data-testid="candidate-card" key={d!.id} className={`candidate ${selected===d!.id?'selected':''} ${run?.state==='stale'?'outdated':''}`} onClick={()=>{setSelected(d!.id);setField('hole_spacing');setView('2d');}}><div className="drawing-thumb"><img src={asset(d!.id,'png')} alt={`${d!.drawing_number} 기술 도면`}/><span>2D / STEP</span></div><div className="candidate-body"><div className="candidate-top"><strong>{d!.drawing_number}</strong><span className="rev">REV. {d!.revision_label}</span></div><p>장착용 브래킷 · {fmt(d!.facts.find(f=>f.field==='material'))}</p><div className="candidate-bottom"><span>간격 <b>{fmt(d!.facts.find(f=>f.field==='hole_spacing'))}</b></span>{c?<span className={`badge ${c.verdict}`}>{c.verdict==='match'?<Check size={12}/>:c.verdict==='unknown'?<AlertTriangle size={12}/>:<X size={12}/>} {labels[c.verdict]}</span>:<span className="unverified">미검증</span>}</div></div></button>)}</div><div className="results-foot"><ShieldCheck size={13}/> 유사도 점수는 적합 판정을 대신하지 않습니다.</div></section>
 <aside className="evidence-panel" data-testid="evidence-panel"><div className="panel-title"><ScanLine size={17}/><h2>도면 근거</h2><span>02</span></div>{doc?<><div className="evidence-heading"><div><strong>{doc.drawing_number}</strong><span>REV. {doc.revision_label} · {doc.active?'유효 도면':'이전 개정판'}</span></div><a href={asset(doc.id,'pdf')} target="_blank" rel="noreferrer" title="원본 PDF 열기"><ArrowUpRight size={19}/></a></div><div className="view-tabs"><button className={view==='2d'?'on':''} onClick={()=>setView('2d')}><FileText size={13}/> 2D 원본</button><button className={view==='3d'?'on':''} onClick={()=>setView('3d')}><Box size={13}/> 3D 형상</button></div>{view==='2d'?<div className="drawing-large"><img src={asset(doc.id,'png')} alt="원본 도면과 근거 영역"/>{bbox&&<span className="bbox" style={{left:bbox[0]*100+'%',top:bbox[1]*100+'%',width:(bbox[2]-bbox[0])*100+'%',height:(bbox[3]-bbox[1])*100+'%'}}/>}</div>:<Model id={doc.id}/>}<div className="evidence-section"><div className="field-label">조건별 근거 <span>PDF 원본 · 1 페이지</span></div>{decision?decision.evidence.map(e=><button key={e.field} className={`evidence-row ${field===e.field?'chosen':''}`} onClick={()=>{setField(e.field);setView('2d');}}><div><span>{fields[e.field]||e.field}</span><b>{fmt(doc.facts.find(f=>f.field===e.field))}</b></div><span className={`badge ${e.verdict}`}>{labels[e.verdict]}</span><ChevronRight size={14}/></button>):<p className="muted">검증을 실행하면 조건별 판정과 원본 위치가 표시됩니다.</p>}{evidence&&<div className={`explanation ${evidence.verdict}`}><ShieldCheck size={16}/><div><strong>{evidence.summary}</strong><p>{evidence.source_refs.length?'강조된 영역은 실제 PDF에서 추출한 표기입니다.':'소재를 확인할 수 있는 표기가 없습니다. 담당자 확인이 필요합니다.'}</p></div></div>}<div className="provenance"><span>검증 방식</span><b>단위 정규화 · 조건 대조</b><span>데이터 버전</span><code>{run?.snapshot_id.slice(0,12)||'실행 전'}</code></div><a className="download" href={asset(doc.id,'step')} download={`${doc.drawing_number}.step`}>STEP 원본 내려받기 <ArrowUpRight size={14}/></a></div></>:<div className="empty"><div><ScanLine size={34}/></div><h3>판단에는 출처가 필요합니다.</h3><p>후보를 선택하면 도면과 3D 형상,<br/>조건별 확인 근거를 볼 수 있습니다.</p><span>NO EVIDENCE, NO ASSUMPTION.</span></div>}</aside></div>
 <section className="run-panel"><button className="run-toggle" onClick={()=>setTimeline(!timeline)}><Activity size={16}/><b>실행 기록 보기</b><span>{events.length} events</span><ChevronRight size={16} className={timeline?'rotated':''}/></button><div className="run-summary">{run?<><span>도구 호출 <b>{run.usage.tool_calls}</b></span><span>모델 호출 <b>{run.usage.model_calls}</b></span><span>토큰 <b>{run.usage.input_tokens+run.usage.output_tokens}</b></span></>:<span>실제 실행 이벤트와 복구 과정을 확인할 수 있습니다.</span>}{running&&<button className="text-button" onClick={()=>api<Run>(`/runs/${run!.id}/cancel`,{method:'POST'}).then(setRun).catch(e=>setError(String(e)))}>실행 취소</button>}</div>{timeline&&<ol data-testid="run-timeline" className="timeline">{events.map(e=><li key={e.seq}><span>{String(e.seq).padStart(2,'0')}</span><i/><div><b>{eventNames[e.kind]||e.kind}</b><code>{e.kind==='tool'?String(e.payload.name):e.kind==='model'?String(e.payload.model_id||''):JSON.stringify(e.payload).slice(0,130)}</code></div><time>{new Date(e.timestamp).toLocaleTimeString('ko-KR',{hour12:false})}</time></li>)}{!events.length&&<p>검증을 시작하면 기록이 나타납니다.</p>}</ol>}</section></>}
 <footer><span><span className="tiny-logo">F</span> FitWitness · Evidence before confidence.</span><span>합성 데이터 연구용 데모 <i/> v0.1.0</span></footer></main></>;
}
createRoot(document.getElementById('root')!).render(<App/>);
